# Generated by Django 2.0 on 2018-01-12 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ownership', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcModel', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('pcTagNo', models.CharField(max_length=120)),
                ('pcModelSeries', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('pcName', models.CharField(max_length=120)),
                ('serialNo', models.CharField(max_length=120)),
                ('operatingSystem', models.CharField(max_length=120)),
                ('processor', models.CharField(max_length=120)),
                ('systemType', models.CharField(max_length=10)),
                ('ram', models.CharField(max_length=8)),
                ('hardDrive', models.CharField(max_length=10)),
                ('remarks', models.CharField(max_length=250)),
                ('startDate', models.DateField(blank=True, default=None, null=True)),
                ('endDate', models.DateField(blank=True, default=None, null=True)),
                ('customerLocation', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ownership.CustomerLocation')),
            ],
        ),
        migrations.CreateModel(
            name='DataCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataCenter', models.IntegerField()),
                ('numberOfRacks', models.IntegerField()),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('customerLocation', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ownership.CustomerLocation')),
                ('tenantlocation', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ownership.TenantLocation')),
            ],
        ),
        migrations.CreateModel(
            name='DCAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=120)),
                ('serialNumber', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licenses', models.CharField(max_length=120)),
                ('principalName', models.CharField(max_length=120)),
                ('dateCreated', models.CharField(max_length=120)),
                ('xmtstaff', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='Ownership.XMTStaff')),
            ],
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialNo', models.CharField(max_length=120)),
                ('tagNo', models.CharField(max_length=120)),
                ('age', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Projector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectorModel', models.CharField(max_length=120)),
                ('projectorYear', models.CharField(max_length=5)),
                ('projectorTag', models.CharField(max_length=120)),
                ('projectorSerialNumber', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('customerLocation', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ownership.CustomerLocation')),
                ('tenantlocation', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ownership.TenantLocation')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagNumber', models.CharField(max_length=255)),
                ('hostname', models.CharField(max_length=120)),
                ('serverModel', models.CharField(max_length=120)),
                ('ipv4', models.CharField(max_length=15)),
                ('domain', models.CharField(max_length=120)),
                ('username', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=120)),
                ('operatingSystem', models.CharField(max_length=120)),
                ('serialNumber', models.CharField(max_length=120)),
                ('productKey', models.CharField(max_length=250)),
                ('processor', models.CharField(max_length=120)),
                ('hardDrive', models.CharField(max_length=8)),
                ('application', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=120)),
                ('startDate', models.DateField(blank=True, default=None, null=True)),
                ('endDate', models.DateField(blank=True, default=None, null=True)),
                ('customerLocation', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ownership.CustomerLocation')),
                ('department', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ownership.Department')),
                ('tenantlocation', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ownership.TenantLocation')),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('softwareName', models.CharField(max_length=120)),
                ('customerLocation', models.ManyToManyField(to='Ownership.CustomerLocation')),
                ('developer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ownership.Developers')),
                ('tenantlocation', models.ManyToManyField(to='Ownership.TenantLocation')),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systemName', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=120)),
                ('customerLocation', models.ManyToManyField(to='Ownership.CustomerLocation')),
                ('developer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ownership.Developers')),
                ('tenantlocation', models.ManyToManyField(to='Ownership.TenantLocation')),
                ('xmtstaff', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ownership.XMTStaff')),
            ],
        ),
        migrations.AddField(
            model_name='computer',
            name='monitor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.Monitor'),
        ),
        migrations.AddField(
            model_name='computer',
            name='projector',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.Projector'),
        ),
        migrations.AddField(
            model_name='computer',
            name='tenantlocation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ownership.TenantLocation'),
        ),
        migrations.AddField(
            model_name='computer',
            name='xmtstaff',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ownership.XMTStaff'),
        ),
    ]
