# Generated by Django 2.0 on 2017-12-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projector',
            name='projectorSerialNumber',
            field=models.CharField(default='NULL', max_length=100),
            preserve_default=False,
        ),
    ]
