# Generated by Django 2.0 on 2017-12-19 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_projector_projectorserialnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projector',
            name='projectorSerialNumber',
        ),
    ]
