# Generated by Django 2.0 on 2017-12-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_remove_projector_projectorserialnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='projector',
            name='projectorSerialNumber',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
