# Generated by Django 2.0 on 2017-12-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ownership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staffID',
            field=models.CharField(default='NULL', max_length=20),
            preserve_default=False,
        ),
    ]
