# Generated by Django 2.0 on 2017-12-19 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ownership', '0002_staff_staffid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='staffID',
        ),
    ]
